# Generated by Django 4.2.7 on 2025-12-31 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(help_text='Steam App ID', unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('name', models.CharField(blank=True, help_text='Alternative name field from CSV', max_length=500)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, help_text='Release date as string from CSV', max_length=100)),
                ('genres', models.CharField(blank=True, help_text='Semicolon-separated genres', max_length=500)),
                ('categories', models.CharField(blank=True, help_text='Semicolon-separated categories', max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendations', models.IntegerField(default=0, help_text='Number of recommendations from CSV')),
                ('developer', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, help_text='Game description (can be added later)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recommendations', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['appid'], name='games_game_appid_f69377_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_year'], name='games_game_release_00eef0_idx'),
        ),
        migrations.AddField(
            model_name='download',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='games.game'),
        ),
        migrations.AddField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user', 'game')},
        ),
    ]
